# Generated by Django 3.2.13 on 2022-06-19 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 18, 27, 41, 636461)),
        ),
    ]
